name: Hello World

# Triggers the workflow on push events to any branch
on:
  push:
    branches: [ "**" ]

jobs:
  hello-world:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Print Hello World
      run: echo "Hello World"