name: Hello World

# Triggers the workflow on push events to any branch
on:
  push:
    branches: [ "**" ]

jobs:
  hello-world:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Print Hello World
      run: echo "Hello World"

  install-copilot-cli:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Install GitHub Copilot CLI
      run: npm install -g @githubnext/github-copilot-cli
      
    - name: Verify installation
      run: github-copilot-cli --version