name: Hello World

on:
  push:
    branches: [ "**" ]
  workflow_dispatch:

jobs:
  run-copilot-cli:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        
    - name: Install GitHub Copilot CLI
      run: npm install -g @github/copilot
      
    - name: Verify installation
      run: copilot --version
    
    - name: Run a sample Copilot command
      run: copilot -p "Tell me about this project" --allow-all-tools
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}

